"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""
a=0
b=1
sumtn=0
x=0
c=0
#n=int(input("Enter number:"))
#print(a)
#print(b)
while c<=4000000:
    c=a+b
    a=b
    b=c
    x+=1
    if c%2==0:
        print(c)
        sumtn=sumtn+c
    #x+=1
    #for n%
    #print(str(x) + ":"+ str(c))
print("Done!")
print("Total is :", sumtn)
